(deffunction do ()
	(bind ?mqd (mq-open /foo (create$ O_CREAT O_RDWR) 0600))
	(println "Created /foo mqueue...")
	(mq-send ?mqd "hi from 2.bat!")
	(println "Sent message to /foo mqueue...")
	(mq-close ?mqd)
	(println "Closed file descriptor for mqueue /foo...")
	(println "Done! Now run ./vendor/clips/clips -f2 example/3.bat to receive your message!"))
(do)
(exit)
