(deffunction do ()
	(println "Opened existing mqueue on disk /foo...")
	(bind ?mqd (mq-open /foo (create$ O_RDWR)))
	(if (not ?mqd) then
		(println "Oops... couldn't open mqueue /foo. Does its file exist on disk? Make sure you run 2.bat first.")
		(return))
	(println "Got " (mq-receive ?mqd))
	(mq-unlink /foo)
	(println "Deleted mqueue file on disk...")
	(mq-close ?mqd)
	(println "Closed file descriptor for mqueue /foo...")
	(println "Done!"))
(do)
(exit)
