(deffunction do ()
	(println "Opened mqueue on disk /foo...")
	(bind ?mqd (mq-open /foo (create$ O_CREAT O_RDONLY) 0600))
	(if (not ?mqd) then
		(println "Oops... couldn't open mqueue /foo. Does its file exist on disk? Make sure you run 4.bat first.")
		(return))
	(bind ?msg (mq-receive ?mqd))
	(while (neq ?msg FALSE) (println "msg: " ?msg) (bind ?msg (mq-receive ?mqd (clock-gettime (create$ 5 0)))))
	(mq-close ?mqd)
	(println "Closed file descriptor for mqueue /foo...")
	(mq-unlink /foo)
	(println "Deleting /foo...")
	(println "Done!"))
(do)
(exit)
